# Pearson's correlation calculations and scatter plot generation for HHS Master's Thesis

# The basics of Pearson's correlation were understood from this tutorial:
# https://www.youtube.com/watch?v=2J_ZlxLeuQU

# Most of this code was then generated by Microsoft CoPilot.

# Female + Male Correllation:

df <- read.csv("C:\\NTNU Master\\R-Data\\R-Data_Pearsons_All_Datapoints.csv")

# Pearson correlations with all info:

cor.test(df$DMOS, df$PESQ, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")

# Correlation with confidence intervals:
# First correlation (DMOS vs PESQ)
result1 <- cor.test(df$DMOS, df$PESQ, method = "pearson")
margin_of_error1 <- (result1$conf.int[2] - result1$conf.int[1]) / 2
formatted_result1 <- paste(round(result1$estimate, 4), "±", round(margin_of_error1, 4))

# Second correlation (DMOS vs ViSQOL.S)
result2 <- cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")
margin_of_error2 <- (result2$conf.int[2] - result2$conf.int[1]) / 2
formatted_result2 <- paste(round(result2$estimate, 4), "±", round(margin_of_error2, 4))

# Third correlation (DMOS vs ViSQOL.A)
result3 <- cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")
margin_of_error3 <- (result3$conf.int[2] - result3$conf.int[1]) / 2
formatted_result3 <- paste(round(result3$estimate, 4), "±", round(margin_of_error3, 4))

# Display the formatted results
formatted_result1
formatted_result2
formatted_result3

# Scatter plots
# Scatter Plot for DMOS vs PESQ with regression line
library(ggplot2)

ggplot(data = df, aes(x = PESQ, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs PESQ Male & Female samples with Regression Line",
       x = "PESQ",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Speech with regression line
ggplot(data = df, aes(x = ViSQOL.S, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Speech Male & Female samples with Regression Line",
       x = "ViSQOL Speech",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Audio with regression line
ggplot(data = df, aes(x = ViSQOL.A, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Audio Male & Female samples with Regression Line",
       x = "ViSQOL Audio",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Female correlation:

df <- read.csv("C:\\NTNU Master\\R-Data\\R-Data_Pearsons_FEMALE.csv")

# Pearson correlations with all info:

cor.test(df$DMOS, df$PESQ, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")

# Correlation with confidence intervals:
# First correlation (DMOS vs PESQ)
result1 <- cor.test(df$DMOS, df$PESQ, method = "pearson")
margin_of_error1 <- (result1$conf.int[2] - result1$conf.int[1]) / 2
formatted_result1 <- paste(round(result1$estimate, 4), "±", round(margin_of_error1, 4))

# Second correlation (DMOS vs ViSQOL.S)
result2 <- cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")
margin_of_error2 <- (result2$conf.int[2] - result2$conf.int[1]) / 2
formatted_result2 <- paste(round(result2$estimate, 4), "±", round(margin_of_error2, 4))

# Third correlation (DMOS vs ViSQOL.A)
result3 <- cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")
margin_of_error3 <- (result3$conf.int[2] - result3$conf.int[1]) / 2
formatted_result3 <- paste(round(result3$estimate, 4), "±", round(margin_of_error3, 4))

# Display the formatted results
formatted_result1
formatted_result2
formatted_result3

# Scatter plots
# Scatter Plot for DMOS vs PESQ with regression line
library(ggplot2)

ggplot(data = df, aes(x = PESQ, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs PESQ Female samples with Regression Line",
       x = "PESQ",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Speech with regression line
ggplot(data = df, aes(x = ViSQOL.S, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Speech Female samples with Regression Line",
       x = "ViSQOL Speech",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Audio with regression line
ggplot(data = df, aes(x = ViSQOL.A, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Audio Female samples with Regression Line",
       x = "ViSQOL Audio",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()


# Male correlation:

df <- read.csv("C:\\NTNU Master\\R-Data\\R-Data_Pearsons_MALE.csv")

# Pearson correlations with all info:

cor.test(df$DMOS, df$PESQ, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")

cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")

# Correlation with confidence intervals:
# First correlation (DMOS vs PESQ)
result1 <- cor.test(df$DMOS, df$PESQ, method = "pearson")
margin_of_error1 <- (result1$conf.int[2] - result1$conf.int[1]) / 2
formatted_result1 <- paste(round(result1$estimate, 4), "±", round(margin_of_error1, 4))

# Second correlation (DMOS vs ViSQOL.S)
result2 <- cor.test(df$DMOS, df$ViSQOL.S, method = "pearson")
margin_of_error2 <- (result2$conf.int[2] - result2$conf.int[1]) / 2
formatted_result2 <- paste(round(result2$estimate, 4), "±", round(margin_of_error2, 4))

# Third correlation (DMOS vs ViSQOL.A)
result3 <- cor.test(df$DMOS, df$ViSQOL.A, method = "pearson")
margin_of_error3 <- (result3$conf.int[2] - result3$conf.int[1]) / 2
formatted_result3 <- paste(round(result3$estimate, 4), "±", round(margin_of_error3, 4))

# Display the formatted results
formatted_result1
formatted_result2
formatted_result3

# Scatter plots
# Scatter Plot for DMOS vs PESQ with regression line
library(ggplot2)

ggplot(data = df, aes(x = PESQ, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs PESQ Male samples with Regression Line",
       x = "PESQ",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Speech with regression line
ggplot(data = df, aes(x = ViSQOL.S, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Speech Male samples with Regression Line",
       x = "ViSQOL Speech",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()

# Scatter Plot for DMOS vs ViSQOL Audio with regression line
ggplot(data = df, aes(x = ViSQOL.A, y = DMOS)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  labs(title = "DMOS vs ViSQOL Audio Male samples with Regression Line",
       x = "ViSQOL Audio",
       y = "DMOS") +
  coord_cartesian(xlim = c(1.5, 5), ylim = c(1.5, 5)) +  # Preserves all. Set axis range from 1.5 to 5
  theme_minimal()
